server.port: ${API_WEB_SERVER_PORT:7002}

context:
  envName: ${CONTEXT_ENV_NAME:nonprod}
  version: ${CONTEXT_VERSION:v1}

client:
  eod:
    request.delay.ms: 110
    baseUrl: eodhistoricaldata.com/api
    security.key: ${CLIENT_API_EOD_SECURITY_KEY:OeAFFmMliFG5orCUuwAKQ8l4WWFQ67YX}
    resource:
      eodExchanges: exchanges-list/
      eodTickers: exchange-symbol-list/
  fmp:
    request.delay.ms: 150
    baseUrl: financialmodelingprep.com/api/v3/
    security.key: ${CLIENT_API_FMP_SECURITY_KEY:0b5b3cc1a7e9a9e7fd45afe22440dcc4}
    resource:
      fmpQuoteTickers: stock/list
      fmpStatementTickers: financial-statement-symbol-lists

kafka.bindings.publisher:
  partitions: 1
  replicas: 3
  eod:
    eodExchanges: eod.${CONTEXT_ENV_NAME}.financial.exchanges.ingestion.${CONTEXT_VERSION}
    eodTickers: eod.${CONTEXT_ENV_NAME}.financial.tickers.ingestion.${CONTEXT_VERSION}
  fmp:
    fmpQuoteTickers: fmp.${CONTEXT_ENV_NAME}.financial.tickers_quote.ingestion.${CONTEXT_VERSION}
    fmpStatementTickers: fmp.${CONTEXT_ENV_NAME}.financial.tickers_statement.ingestion.${CONTEXT_VERSION}

spring:
  # Spring Kafka
  kafka:
    header.traceId: x-trace-id
    bootstrap-servers: ${KAFKA_BROKER_ADDRESS:localhost:9092}
    properties:
      max.request.size: 2000000
      ssl.endpoint.identification.algorithm: ${SECURITY_SSL_ENDPOINT_ID_ALGO}
      sasl.mechanism: ${SECURITY_SASL_MECHANISM}
      security.protocol: ${SECURITY_PROTOCOL}
      sasl.jaas.config: ${SECURITY_SASL_JAAS_CONFIG}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ingest_financial_exchange_tickers_fmp_consumer_ticker_id_00000002
      auto-offset-reset: earliest
      properties.spring.json.trusted.packages: "*"

  # Spring WebFlux
  codec:
    max-in-memory-size: "20MB"
