server.port: ${API_WEB_SERVER_PORT:7001}

context:
  envName: ${CONTEXT_ENV_NAME:dev01}

client.api:
  request.delay.ms: 100
  fmp:
    baseUrl: financialmodelingprep.com/api/v3/
    security.key: 7386dd583165a61d45491bdec637e692
    resource:
      allTickers: stock/list
      incomeStatement: income-statement/
      balanceSheet: balance-sheet-statement/
      cashFlow: cash-flow-statement/
  eod:
    baseUrl: eodhistoricaldata.com/api
    security.key: 5f54dd914e6225.67240107
    resource:
      eodExchanges: exchanges-list/
      eodTickers: exchange-symbol-list/
      eodFinancials: fundamentals/

spring:
  # Spring Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_ADDRESS:localhost:9092}
    properties:
      max.request.size: 2000000
      ssl.endpoint.identification.algorithm: ${SECURITY_SSL_ENDPOINT_ID_ALGO}
      sasl.mechanism: ${SECURITY_SASL_MECHANISM}
      security.protocol: ${SECURITY_PROTOCOL}
      sasl.jaas.config: ${SECURITY_SASL_JAAS_CONFIG}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # Spring WebFlux
  codec:
    max-in-memory-size: "20MB"

  # Spring Data JPA
  data:
    mongodb:
      host: ${DATA_MONGODB_HOST:localhost}
      port: ${DATA_MONGODB_PORT:27017}
